name: kidnation_mobile_games
description: KidNation Flutter mini-game prototypes.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  audioplayers: ^6.8.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/audio/bubble_blast/
  uses-material-design: true
